### ISSUE TITLE
Help Request - Runtime Screen Calibration & Larger Keypad For Number Input Fields

### ISSUE THREAD

**Issue by ee-boi** [Pconti31/GUIslice-Solutions#11]
Hi @Pconti31, been awhile, hope this note finds you well!

I am writing today to see if I can get your support on implementing two different solutions:

1. I would like to be able to have a button that a user can press that launches a calibration screen, similar to the one used in [the calibration example here](https://github.com/ImpulseAdventure/GUIslice/blob/master/examples/arduino/diag_ard_touch_calib/diag_ard_touch_calib.ino) and then upon completion it saves the data using 
`gslc_SetTouchRemapCal(&m_gui, nXMin, nXMax, nYMin, nYMax);`
`gslc_SetTouchRemapYX(&m_gui, nRemapYX);`
`gslc_SetTouchRemapEn(&m_gui, true); `

I took a look at the example in the link above and it is a great sketch, but I was having trouble deciphering it and then on top of that how to integrate it into an existing project I am working on and was wondering if you wouldn't mind helping/making an example? I envision this being essentially a button on the main page that changes to a calibration page, runs the calibration routine, spits out the values and then the user can hit a button to save values & go back to the previous page or to cancel (not save) the values and go back to the previous page. I feel like this is a tall order, so if you don't have time/don't feel like doing this I understand. 

2. This should be a little easier - is there a way to make the keypad popup from a number input field larger? As in - larger as a whole, and larger buttons on the keypad? I took a look through the source code for the keypad and couldn't figure out where to change this.

**Specs I am using (for reference):**
- [Adafruit Metro M0 express MCU (SAMD21, arm cortex M0+)](https://www.adafruit.com/product/3505)
- [ILI9341 display](https://www.adafruit.com/product/1770)
- platformIO via VScode as environment
- GUIslice config selected: Custom (as previously posted in closed issue https://github.com/ImpulseAdventure/GUIslice/issues/509)
- Adafruit GFX driver

As always many thanks in advance for any and all advice/help you share.

ee-boi

**Comment by Pconti31** [comment]
@ee-boi Number 2 is the easy one.  The GUIslice API allows you to customize the keypad, changing font, and size of buttons giving you a larger keypad.
The APi isn't easy to understand so just use the Builder and you will see how I support trhis.
Inside the Builder, Edit->Options, Use the KeyPad<Num or Alpha> tab depending upon which one you are going to use.
Start with Use Default Button Sizes? and change from true to to false so you can modify sizes.
then enter new sizes and if you want change the font.
Create a new project or edit and existing one.  

As for number one. I'm not familar with Calvin's calbration code but I'll take a look.  If I can't work it out you might be able to get help or ideas from Calvin by posting in his GUIslice/Discussion section.  He seems to have started to look at it again...
Paul--

**Comment by ee-boi** [comment]
@Pconti31 ah changing the keypad was extremely simple, thank you for that, did it in the builder like you advised and that worked perfectly.

Appreciate you taking at look at the calibration solution, will post over on the GUIslice Discussion section depending on what your thoughts are. Appreciate your help as always!!!

**Comment by Pconti31** [comment]
@ee-boi I have started to code a solution for you.  No idea if it will work or not. I am choosing to store the results of the calibration on an SD card.

Now, in looking over Calvin's code I realized a chicken and egg problem.  If you haven't run Calibration before what are the odds of the user being able to trigger a button to start calibration?  Anyway, I'm ignoring that for the moment and plowing ahead.

If you think this could be a real problem then a possible solution might be at startup to first test to see if calibration values are already stored on the SD card and if so go on our way with these values calling
```
gslc_SetTouchRemapCal(&m_gui, nXMin, nXMax, nYMin, nYMax);
gslc_SetTouchRemapYX(&m_gui, nRemapYX);
gslc_SetTouchRemapEn(&m_gui, true); 
```
However, if these values are not currently stored on the SD card then immediatily run the calibration code and afterwards jump into your App's main page.  You could of course have an addition setup button in your app that could run calibration at a later date if fine tuning was ever needed.

Let me know what you think.  
Paul--

**Comment by ee-boi** [comment]
@Pconti31 First and foremost - thank you for the help on the solution!

As far as the chicken & egg problem - here is what I am thinking - at least for my project it may not matter...for my application (device) I initially calibrated the first prototype and then created 3 more subsequent prototypes all using the exact same hardware, and still using the initial prototypes screen calibration values. What I noticed was the subsequent 3 prototypes were pretty close, but needed a "fine tune" to the calibration to get them perfect. That is why I was wondering if a page for calibration could be made so that during quality testing and/or if the user wanted to "tweak" them and improve the calibration for their device they could do so (and knowing that every resistive touch panel is slightly different).

In my project I do have some code that only runs once at initial power-on, so maybe I could add it in that on initial power-on the display automatically jumps to the calibration page, the user can calibrate, and then once complete they can hit a button that saves the values in flash and jumps back to the main page. Then as you mention if they ever wanted to re-run calibration they could hit a button and it would pull the page (for calibration) up again.

I think saving them for an SD is fine, I use a library that stores things in flash memory ([here](https://github.com/cmaglie/FlashStorage)) in my project so I should be able to just swap your code for writing variables to SD over to writing the variables in flash.

Thank you!!! - ee-boi

**Comment by Pconti31** [comment]
@ee-boi Hmm, seems your library also has a EEPROM-like API.  I can make  two #defines
```
#define USE_SD_INTERFACE
#define USE_EEPROM_INTERFACE
```
instead my TFT_Calibration.h file.
and use the  Arduino EEPROM API since i'm using a arduino mega for this anyway.
Then users can use either the SD interface or EEPROM depending upon their enironment.

As your screens seem to be quite close in calibration I agree you will only need to have users fine tine it.
Paul--

**Comment by ee-boi** [comment]
@Pconti31 sounds good! I do like your idea of "forcing" calibration on initial power-on too, just in case for some reason it is wildly different for a given touch display. I will plan on including that in my "initial power-on" code too, that way the user always has a functional display.

**Comment by Pconti31** [comment]
@ee-boi Good news I have a sample App working using my new TFT_Calibration.(h,cpp)
class.   It does need some cleanup work and I need to stop working on it now.
I have some commitments for tomorrow so thursday will be earliest I can finish up.
Paul--

**Comment by ee-boi** [comment]
@Pconti31 Awesome! And no problem, I am grateful for any time and availability you have to spend on helping with this solution. Look forward to seeing it!

**Comment by Pconti31** [comment]
@ee-boi Completed.  Checkout apps/runtime_calibration

NOTE: There is a small bug where screen repaint of the page you are coming from gets redrawn very briefly before calibration starts.  Annoying but I have no idea why...
Paul--

**Comment by ee-boi** [comment]
@Pconti31 Awesome! Ill take a look at it over the weekend, going to try to also integrate it into my project as well. Will keep you posted. Thank you!

**Comment by ee-boi** [comment]
@Pconti31 Hi Paul, unfortunately haven't had too much time to play around with this yet, although I am getting to it. 

By chance are you able to share the files so I can open in the builder? Or can I just open it with the .prj file with the builder? I have some time to work on it (albeit offline) and want to look at getting it integrated with my project (that I made with the builder).

Thank you!

**Comment by Pconti31** [comment]
@ee-boi The README.md tells you that you can open the .prj file and to make modifications using the OPTIONS tab, like changing screen size, using PlatformIO, TFT_eSPI etc...

Don't forget to read the NOTES and WARNINGs sections inside "TFT_Calibration.h" for TFT_Calibration class usage.

One thing that may not be obvious is how to use this new class with my screen saver class
since they both require calling their own update function.
The answer is to ignore the Calibration update() function and and instead do this...

```
loop() {
 .
 .
 .
  
  if (calibration.isActive()) {
    loop();
  } else {
  
    // Our ScreenMgr calls gslc_Update when required
    // DO NOT call it directly or your screen will get messed up!
    //gslc_Update(&m_gui);
    screenMgr.update();
}
```
    
Post if you end up with any problems or if you don't understand something.
Paul--

**Comment by ee-boi** [comment]
@Pconti31 Ah, I should always know better to read first. Thank you for the help/tips. Will do!

**Comment by ee-boi** [comment]
@Pconti31 ok finally had some time to work on this a bit. I took the code you posted and modified it a bit to also include and use the FlashStorage.h library. This was necessary as I am using an ARM Cortex M0+ based board that doesn't use EEPROM or have an SD card (for this particular project). (ok I suppose EEPROM would still work but the Flash Storage library works nicely with this boards). Please see attached and let me know what you think, it seems to work well for my  usage/project.

The only issue I encountered was the DEBUG Print in the TFT_Calibration.h class did not work at all for me, attempting to use either "1" or "2", it never printed anything to serial and I am not sure why. I ended up just making the example "Do Something" button print the stored and defined values so I could determine if the flash storage was working. 

Also I see the bug where the screen flashes right before entering the calibration routine, I will take a look as I integrate into my project and let you know if I can figure that out.

[runtime_calib_flashstorage.zip](https://github.com/Pconti31/GUIslice-Solutions/files/14953446/runtime_calib_flashstorage.zip)

- ee-boi

**Comment by Pconti31** [comment]
@ee-boi I noticed one bug with my prints
```
  #define CALIB_DEBUG2_PRINT(sFmt, ...)                          \
          do {                                                  \
            if (DEBUG_ERR >= 2) {                               \
              gslc_DebugPrintf(sFmt,__VA_ARGS__);               \
            }                                                   \
          } while (0)
```
should be:
```
  #define CALIB_DEBUG2_PRINT(sFmt, ...)                          \
          do {                                                  \
            if (DEBUG_CALIB >= 2) {                               \
              gslc_DebugPrintf(sFmt,__VA_ARGS__);               \
            }                                                   \
          } while (0)
```
Also you may need to modify your config/*.h file to set  
```
#define DEBUG_ERR               1   // 1,2 to enable, 0 to disable
```
Paul--

**Comment by Pconti31** [comment]
@ee-boi Your modifications look fine to me.  I'll update the comments and check your version in.
Although, I'll keep the default I originally had.
Paul--

**Comment by ee-boi** [comment]
@Pconti31 Awesome! I updated the debug code with what you posted previously and changed `#define DEBUG_ERR` to `2` in my config but still get nothing printed to Serial. it must be something upstream I changed awhile back (I copied my project config of GUISLICE over for this). No matter, it all appears to be working fine so I am going to work on integrating it into my project. Will let you know if I have any other questions.

**Comment by ee-boi** [comment]
@Pconti31 Ok - I did get the debug error working, it was an issue on my end and I changed something dumb. All good. One question for you though now that I can see the debug print out to serial - I modified line 100 in the TFT_Calibration.cpp file to ` CALIB_DEBUG2_PRINT("Touch Config values from Flash\n", "");` as I did not have a value to give for the second argument. When the code runs it prints the following: `Touch Calibration values written to FLASH STORAGE 64278`, not sure what the `64728` is but is there something I can put in there as placeholder?

**Comment by Pconti31** [comment]
@ee-boi Your debug looks fine to me. I suppose you could try:
```
    CALIB_DEBUG2_PRINT("Touch Config values from Flash %s\n", " ");
```
Although why is beyond me...
If it works for you let me know.
You can also do a pull request or I can make the change.
Paul--

**Comment by Pconti31** [comment]
@ee-boi In looking over your code again I found the problem.
Its not line 100 but around line 509 inform()
```
  CALIB_DEBUG_PRINT("Touch Calibration values written to FLASH STORAGE %d\n", "");
```
this should be
```
  CALIB_DEBUG_PRINT("Touch Calibration values written to FLASH STORAGE\n", "");
```
Paul--

**Comment by ee-boi** [comment]
@Pconti31 

Confirmed - that fixed it. Working on integrating into my project, will post back if there's and issue or if I have a question. 

Thank you again Paul! Appreciate you!

**Comment by Pconti31** [comment]
@ee-boi Since I haven't heard back I assume things are going ok.
I'll reopen this if any problems come up.
Paul--

**Comment by ee-boi** [comment]
Sorry Paul,

Been sidetracked as of late and progress has been slow. I did get the bones ported over to my project (the GUISlice Builder portion) but have yet to integrate the functional code. 

Hoping to have some time here in the next couple of weeks to do it, and will reach out if there is any questions.

Thanks,
ee-boi

**Comment by ee-boi** [comment]
@Pconti31 

Finally got around to getting this integrated into my own project. Seems to be working well, although I am having one issue that have not been able to figure out....

Line 37 of TFT_Calibration.cpp has this ``` m_nRotation = m_pGui->nRotation;``` line which I believe is used to store the current screen rotation, so that way it can be restored after calibration is completed line 457 restores it with ```gslc_GuiRotate(m_pGui, m_nRotation);```. 

I only use rotations `1` or `3` for my project, so Line 37 should evaluate to `1` or `3`,  but for some reason when checked via my debugger, `nRotation` in Line 37 evaluates to `0`, so when calibration is completed, it turns my screen lengthwise which is not wanted.

Now - here is the strange part, I ran your code using my same config file and checked Line 37 of TFT_Calibration.cpp with my debugger and it evaluates to `1`, which is correct.

Any ideas on what is going on here?

**Comment by ee-boi** [comment]
Ok I figured out why this is happening but not how to fix it. For whatever reason when my project starts up the TFT_Calibration.cpp file evaluates before the Guislice.c does so upon initialization line 37 of TFT_Calibration.cpp reads `0` first, then after Guislice.c runs and it is swapped to `1`, but the value m_nRotation in the TFT_Calibration.cpp variable is already saved.

Thoughts on how to get TFT_Calibration.cpp to run after Guislice.c runs at startup?

**Comment by ee-boi** [comment]
Ok did a temporary (or maybe permanent) workaround for this, I added a public function in TFT_Calibration.cpp as follows
`uint8_t TFT_Calibration::storeRotation(){
  m_nRotation = m_pGui->nRotation;
}`

and then call that function during the button press to change to calibration page. Seems to be working.

Now I have one more issue that I do not understand - when I do the initial calibration, all seems fine and when I go back out to the previous page from the calibration page and then hit the "calibrate" button again the gui locks up and I have to reset the board?

Any ideas on that??

**Comment by Pconti31** [comment]
@ee-boi For the first issue, 0 means native rotation which seems to not be what you want so setting
gslc_GuiRotate(m_pGui, 1) before calling calibration.init() would have worked.  Setting rotation inside the GUIsliceBuilder on the E_PROJECT_OPTIONS tab Screen Rotation [0-3 or -1 default] to 1 would do that for you.

For the second issue you should be getting a crash output in your Serial Monitor unless you are getting a hang.
If its crash post your debug output for me to look at...
If its a hang you will need to do tracing until you figure things out.
What happens if you turn your mcu on and off after calibration do the changed values appear to be used in the new reboot or do they go back to the config file values?

Paul--

**Comment by ee-boi** [comment]
@Pconti31 

Ok - got it figured out, appreciate your help once again (x1000). 

Both issues happened to be related.

As for for the first issue in `setup()` having the call to `calibration.init()` AFTER the call to `InitGUIslice_gen();` fixed the problem and `m_nRotation` receives the value from `m_pGui->nRotation` and loads it correctly. 

Now as for issue 2 - it was from the function I created to store rotation to correct for issue 1. I had:
```
uint8_t TFT_Calibration::storeRotation(){
  m_nRotation = m_pGui->nRotation;
}
```
 
which should have been:
```
uint8_t TFT_Calibration::storeRotation(){
  m_nRotation = m_pGui->nRotation;
  return m_nRotation;
}
```

Now - that solved my problem of the hang and initial rotation was loading correctly but I also had an issue where if the user inverted the screen, say from rotation 1 to rotation 3, after calibration it would restore to calibration 1, and not 3.

So within `TFT_Calibration::run()` I added the last line below `m_nRotation = m_pGui->nRotation;`  which pulls current `nRotation` and stores it in `m_nRotation` which seems to have done the trick and upon calibration completion, it restores it to rotation 3 (inverted) if the user had the display rotated that way before starting calibration. I also got rid of my function `uint8_t TFT_Calibration::storeRotation()` as it seemed no longer necessary.

```
void TFT_Calibration::run() {
  // begin by initializing our control variables
  m_nPointFinalX = -1;
  m_nPointFinalY = -1;
  m_bTouchCalFail = false;
  m_bRemapYX = false;
  m_bTouchCoordValid = false;
  m_nPointBufX = 0;
  m_nPointBufY = 0;
  m_nPointBufCnt = 0;
  //!storeRotation(); //!
  m_nRotation = m_pGui->nRotation;

... the rest of the run() function
```
 

All that said - going to do a little more testing but seems to be working wonderfully thus far. Have not figured out why the previous screen flashes before the calibration routine starting yet, but that is a tiny bug I can live with if I don't solve it.

Will report back here if there is any further issues/questions. I think we can close this again for now! 

Paul - I want to express my gratitude in your help, this project would not be where it was without your support. Thank you. ee-boi

**Comment by ee-boi** [comment]
@Pconti31 posting so you don't close this quite yet...ran into two issues I have questions about. On mobile right now so will type them up in more detail later:

1. In a previous comment you mentioned using the calibration class with the screen saver class...is that code supposed to go into the main loop? I can give more details but I am curious about something...

2. I added two toggle buttons to the calibration page. 1 toggle is just to test calibration (the thinking being if you calibrate you should be able to accurately toggle a switch) the other is a "safety lock" of sorts that the user must toggle to "on" or "checked" before they can save the calibration values. This is so the user can't accidentally calibrate it wrong and then hit the save values button that stores them to flash because then they would never be able to get back to the calibration page if the calibration was off significantly! My issue is - I noticed that when one toggle is pressed, it also flips the other toggle as well for some reason. I notice that it also is flipping other toggle buttons I used in other pages, but I can't find any links in the code that would do this? I do not have any group IDs set on any of the toggle buttons and they are all stored in flash memory. I am going to mess with it a little more but if I don't get anywhere I will try to recreate and post an example.

**Comment by Pconti31** [comment]
@ee-boi The bug with toggle button being grouped together is my fault.
You need to edit XTogglebtn.h I'll make a pull request but who knows when or if calvin will get around to it.
The problem is with the flash implementation I thought no group was equal to zero but it's actually -6999
So change lines 211 and 253 from 0, to
```
        -6999,   \
```
Paul--

**Comment by ee-boi** [comment]
@Pconti31 for the toggle bug, that worked, appreciate that.

As for where to put `calibration.update()` ... in [this reply](https://github.com/Pconti31/GUIslice-Solutions/issues/11#issuecomment-2025111167) earlier in the thread, did you mean to add this code into my `loop()` in `main.cpp`? or was that in `calibration.cpp`? I am thinking it is the later.

I wondered if there is any issue doing something like the below in my `main.cpp` loop to keep my code lean & mean? or would this pose a problem?

```
  if(calibration_start_flag == true){
    calibration.update();
    if (calibration.getStatus() != CALIBR_UNDEFINED) {
      if (calibration.getStatus() == CALIBR_SUCCESS) {
        gslc_ElemSetTxtCol (&m_gui, m_pElemE_CALIB_STATUS_CLBPG1, GSLC_COL_GREEN);
        gslc_ElemSetTxtStr(&m_gui,m_pElemE_CALIB_STATUS_CLBPG1,"CALIBRATION SUCCESS");
      } else {
        gslc_ElemSetTxtCol (&m_gui, m_pElemE_CALIB_STATUS_CLBPG1, GSLC_COL_RED);
        gslc_ElemSetTxtStr(&m_gui,m_pElemE_CALIB_STATUS_CLBPG1,"CALIBRATION FAILURE");
      }
    }
  }
  else{
    gslc_Update(&m_gui);
  }
```

Obviously setting a flag to true when the calibration button is clicked and then false when the "done" button is clicked. Any issues with this?

**Comment by Pconti31** [comment]
@ee-boi 
Of course you put your code inside main.cpp but If you are combining with screen manager then your code is very bad.
If you are using Screen Manager you call its update function you MUST NOT call either calibration.update() or  gslc_Update(&m_gui) directly.  Let Screen Manager choose when to call gslc_Update().
The problem being setting your text fields for success ot failures...
maybe this would work?
```
  if(calibration_start_flag == true){
   if (calibration.isActive()) { // better be true if you have calibration_start_flag=true
    calibration.loop();
    if (calibration.getStatus() != CALIBR_UNDEFINED) {
      if (calibration.getStatus() == CALIBR_SUCCESS) {
        gslc_ElemSetTxtCol (&m_gui, m_pElemE_CALIB_STATUS_CLBPG1, GSLC_COL_GREEN);
        gslc_ElemSetTxtStr(&m_gui,m_pElemE_CALIB_STATUS_CLBPG1,"CALIBRATION SUCCESS");
      } else {
        gslc_ElemSetTxtCol (&m_gui, m_pElemE_CALIB_STATUS_CLBPG1, GSLC_COL_RED);
        gslc_ElemSetTxtStr(&m_gui,m_pElemE_CALIB_STATUS_CLBPG1,"CALIBRATION FAILURE");
      }
      calibration.setStatus(CALIBR_UNDEFINED);
      calibration_start_flag = false;
    }
 
  } else {
    // Our ScreenMgr calls gslc_Update when required
    // DO NOT call it directly or your screen will get messed up!
    //gslc_Update(&m_gui);
    screenMgr.update();
  }
  ```  

Paul--

**Comment by ee-boi** [comment]
Paul - hope you are doing well. Code for screen calibration is working great. Closing this out. As always I feel I owe you more than this - thank you so much! My project wouldn't be possible without your support. Cheers!
